services:
    postgres_db:
        image: postgres:13
        container_name: postgres_db
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "${POSTGRES_PORT}:5432"
        restart: always
    # fastapi:
    #     build: .
    #     restart: always
    #     container_name: fastapi_app
    #     ports:
    #         - "8000:8000"
    #     depends_on:
    #         - postgres_db
    #     env_file:
    #         - .env
    #     volumes:
    #         - .:/app
    #     environment:
    #         - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
